const mockRecipes = [
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: true,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 11,
    gaps: "no",
    preparationMinutes: 10,
    cookingMinutes: 45,
    aggregateLikes: 1866,
    healthScore: 100,
    creditsText: "pinkwhen.com",
    sourceName: "pinkwhen.com",
    pricePerServing: 300.45,
    id: 715415,
    title: "Red Lentil Soup with Chicken and Turnips",
    readyInMinutes: 55,
    servings: 8,
    sourceUrl:
      "https://www.pinkwhen.com/red-lentil-soup-with-chicken-and-turnips/",
    image: "https://img.spoonacular.com/recipes/715415-312x231.jpg",
    imageType: "jpg",
    summary:
      'Red Lentil Soup with Chicken and Turnips might be a good recipe to expand your main course repertoire. This recipe serves 8 and costs $3.0 per serving. One serving contains <b>477 calories</b>, <b>27g of protein</b>, and <b>20g of fat</b>. It is brought to you by Pink When. 1866 people have tried and liked this recipe. It can be enjoyed any time, but it is especially good for <b>Autumn</b>. From preparation to the plate, this recipe takes approximately <b>55 minutes</b>. It is a good option if you\'re following a <b>gluten free and dairy free</b> diet. Head to the store and pick up salt and pepper, canned tomatoes, flat leaf parsley, and a few other things to make it today. Overall, this recipe earns a <b>spectacular spoonacular score of 99%</b>. If you like this recipe, you might also like recipes such as <a href="https://spoonacular.com/recipes/red-lentil-and-chicken-soup-682185">Red Lentil and Chicken Soup</a>, <a href="https://spoonacular.com/recipes/red-lentil-and-chicken-soup-1058971">Red Lentil and Chicken Soup</a>, and <a href="https://spoonacular.com/recipes/red-lentil-soup-34121">Red-Lentil Soup</a>.',
    cuisines: [],
    dishTypes: ["lunch", "soup", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free"],
    occasions: ["fall", "winter"],
    spoonacularScore: 99.42384338378906,
    spoonacularSourceUrl:
      "https://spoonacular.com/red-lentil-soup-with-chicken-and-turnips-715415",
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 2,
    gaps: "GAPS_4",
    preparationMinutes: null,
    cookingMinutes: null,
    aggregateLikes: 207,
    healthScore: 100,
    creditsText: "Full Belly Sisters",
    license: "CC BY-SA 3.0",
    sourceName: "Full Belly Sisters",
    pricePerServing: 178.37,
    id: 716406,
    title: "Asparagus and Pea Soup: Real Convenience Food",
    readyInMinutes: 20,
    servings: 2,
    sourceUrl:
      "https://fullbellysisters.blogspot.com/2011/03/asparagus-and-pea-soup-real-convenience.html",
    image: "https://img.spoonacular.com/recipes/716406-312x231.jpg",
    imageType: "jpg",
    summary:
      'Asparagus and Pea Soup: Real Convenience Food requires approximately <b>20 minutes</b> from start to finish. Watching your figure? This gluten free, dairy free, paleolithic, and lacto ovo vegetarian recipe has <b>217 calories</b>, <b>11g of protein</b>, and <b>8g of fat</b> per serving. This recipe serves 2. For <b>$1.78 per serving</b>, this recipe <b>covers 25%</b> of your daily requirements of vitamins and minerals. <b>Autumn</b> will be even more special with this recipe. It works well as a hor d\'oeuvre. 207 people have tried and liked this recipe. It is brought to you by fullbellysisters.blogspot.com. A mixture of vegetable broth, evoo, garlic, and a handful of other ingredients are all it takes to make this recipe so yummy. All things considered, we decided this recipe <b>deserves a spoonacular score of 96%</b>. This score is outstanding. Try <a href="https://spoonacular.com/recipes/asparagus-and-pea-soup-real-convenience-food-1393979">Asparagus and Pea Soup: Real Convenience Food</a>, <a href="https://spoonacular.com/recipes/asparagus-and-pea-soup-real-convenience-food-1376201">Asparagus and Pea Soup: Real Convenience Food</a>, and <a href="https://spoonacular.com/recipes/asparagus-and-pea-soup-real-convenience-food-1362341">Asparagus and Pea Soup: Real Convenience Food</a> for similar recipes.',
    cuisines: [],
    dishTypes: [
      "antipasti",
      "soup",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre",
    ],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "lacto ovo vegetarian",
      "primal",
      "vegan",
    ],
    occasions: ["fall", "winter"],
    spoonacularScore: 99.41313934326172,
    spoonacularSourceUrl:
      "https://spoonacular.com/asparagus-and-pea-soup-real-convenience-food-716406",
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 5,
    gaps: "no",
    preparationMinutes: null,
    cookingMinutes: null,
    aggregateLikes: 19,
    healthScore: 83,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 69.09,
    id: 644387,
    title: "Garlicky Kale",
    readyInMinutes: 45,
    servings: 2,
    sourceUrl: "https://www.foodista.com/recipe/J2FTJBF7/garlicky-kale",
    image: "https://img.spoonacular.com/recipes/644387-312x231.jpg",
    imageType: "jpg",
    summary:
      'Garlicky Kale requires approximately <b>45 minutes</b> from start to finish. This side dish has <b>170 calories</b>, <b>2g of protein</b>, and <b>15g of fat</b> per serving. This recipe serves 2. For <b>69 cents per serving</b>, this recipe <b>covers 17%</b> of your daily requirements of vitamins and minerals. 19 people have made this recipe and would make it again. This recipe from Foodista requires balsamic vinegar, garlic, curly kale, and olive oil. It is a good option if you\'re following a <b>gluten free, dairy free, paleolithic, and lacto ovo vegetarian</b> diet. With a spoonacular <b>score of 99%</b>, this dish is outstanding. Try <a href="https://spoonacular.com/recipes/garlicky-kale-248759">Garlicky Kale</a>, <a href="https://spoonacular.com/recipes/garlicky-kale-1267347">Garlicky Kale</a>, and <a href="https://spoonacular.com/recipes/garlicky-kale-1584523">Garlicky Kale</a> for similar recipes.',
    cuisines: [],
    dishTypes: ["side dish"],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "lacto ovo vegetarian",
      "primal",
      "whole 30",
      "vegan",
    ],
    occasions: [],
    spoonacularScore: 98.93541717529297,
    spoonacularSourceUrl: "https://spoonacular.com/garlicky-kale-644387",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 10,
    gaps: "no",
    preparationMinutes: 10,
    cookingMinutes: 480,
    aggregateLikes: 57,
    healthScore: 100,
    creditsText: "pinkwhen.com",
    sourceName: "pinkwhen.com",
    pricePerServing: 270.41,
    id: 715446,
    title: "Slow Cooker Beef Stew",
    readyInMinutes: 490,
    servings: 6,
    sourceUrl: "https://www.pinkwhen.com/slow-cooker-beef-stew-recipe/",
    image: "https://img.spoonacular.com/recipes/715446-312x231.jpg",
    imageType: "jpg",
    summary:
      'If you want to add more <b>gluten free and dairy free</b> recipes to your recipe box, Slow Cooker Beef Stew might be a recipe you should try. One serving contains <b>434 calories</b>, <b>44g of protein</b>, and <b>12g of fat</b>. This recipe serves 6. For <b>$2.7 per serving</b>, this recipe <b>covers 45%</b> of your daily requirements of vitamins and minerals. It works best as a main course, and is done in approximately <b>8 hours and 10 minutes</b>. If you have green onions, carrots, celery, and a few other ingredients on hand, you can make it. This recipe is liked by 57 foodies and cooks. <b>Autumn</b> will be even more special with this recipe. It is brought to you by Pink When. Taking all factors into account, this recipe <b>earns a spoonacular score of 99%</b>, which is awesome. Similar recipes include <a href="https://spoonacular.com/recipes/slow-cooker-beef-stew-1578321">Slow Cooker Beef Stew</a>, <a href="https://spoonacular.com/recipes/slow-cooker-beef-stew-1241707">Slow Cooker Beef Stew</a>, and <a href="https://spoonacular.com/recipes/slow-cooker-beef-stew-1281171">Slow Cooker Beef Stew</a>.',
    cuisines: [],
    dishTypes: ["lunch", "soup", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free"],
    occasions: ["fall", "winter"],
    spoonacularScore: 98.83934020996094,
    spoonacularSourceUrl:
      "https://spoonacular.com/slow-cooker-beef-stew-715446",
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 9,
    gaps: "no",
    preparationMinutes: null,
    cookingMinutes: null,
    aggregateLikes: 53,
    healthScore: 96,
    creditsText: "foodandspice.com",
    sourceName: "foodandspice.com",
    pricePerServing: 168.43,
    id: 782601,
    title: "Red Kidney Bean Jambalaya",
    readyInMinutes: 45,
    servings: 6,
    sourceUrl:
      "https://www.foodandspice.com/2016/05/red-kidney-bean-jambalaya.html",
    image: "https://img.spoonacular.com/recipes/782601-312x231.jpg",
    imageType: "jpg",
    summary:
      'Red Kidney Bean Jambalayan is a main course that serves 6. One portion of this dish contains approximately <b>18g of protein</b>, <b>6g of fat</b>, and a total of <b>393 calories</b>. For <b>$1.68 per serving</b>, this recipe <b>covers 33%</b> of your daily requirements of vitamins and minerals. 53 people were glad they tried this recipe. A mixture of vegetable stock, tomatoes, onion, and a handful of other ingredients are all it takes to make this recipe so flavorful. It is a good option if you\'re following a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan</b> diet. This recipe is typical of Cajun cuisine. It is brought to you by foodandspice.blogspot.com. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. Overall, this recipe earns a <b>tremendous spoonacular score of 99%</b>. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/red-kidney-bean-jambalaya-1407231">Red Kidney Bean Jambalaya</a>, <a href="https://spoonacular.com/recipes/red-kidney-bean-salad-94525">Red Kidney Bean Salad</a>, and <a href="https://spoonacular.com/recipes/red-kidney-bean-curry-80686">Red Kidney Bean Curry</a>.',
    cuisines: ["Creole", "Cajun"],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    occasions: [],
    spoonacularScore: 98.80960845947266,
    spoonacularSourceUrl:
      "https://spoonacular.com/red-kidney-bean-jambalaya-782601",
  },
];

module.exports = mockRecipes;